### ISSUE TITLE
Remove this

### ISSUE THREAD

**Issue by hashaam-zahid** [NathanBlackburnDev/CS50-solutions#5]
I am writing to bring to your attention a repository on GitHub CS50 that appears to be in violation of the academic policy of Harvard University. The repository in question contains solutions to assignments from the CS50x course, offered by Harvard's Extension School. Remove or make it private 
Looking forward

**Comment by blacknand** [comment]
Thank you for bringing this to my attention. I have looked into this, and the repository is not in violation. Please look at this [CS50 reddit thread](https://www.reddit.com/r/cs50/comments/b25gq1/so_is_it_okay_to_post_all_the_solutions_for_cs50/)
